DROP TABLE  if EXISTS ye_task;
DROP TABLE  if EXISTS ye_user;

CREATE  TABLE ye_user(
  id int NOT NULL ,
  login_name VARCHAR(50) NOT NULL UNIQUE ,
  name VARCHAR (64) NOT NULL ,
  password VARCHAR (50)NOT NULL,
  salt VARCHAR (50) NOT NULL,
  roles VARCHAR (50) NOT NULL,
  register_date TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

create table ye_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
  primary key (id)
);
